export const LOAD_TICKETS_SUCCESS = 'LOAD_TICKETS_SUCCESS';
export const SET_TICKETS_PAGE = 'SET_TICKETS_PAGE';
export const SET_TICKETS_PER_PAGE = 'SET_TICKETS_PER_PAGE';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const LOGOUT = 'LOGOUT';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';